apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: 0paque
data:
  POSTGRES_DB: {{ .Values.POSTGRES_DB | b64enc }}
  POSTGRES_USER: {{ .Values.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | b64enc }}
  SECRET_KEY: {{ .Values.SECRET_KEY | b64enc }}
